repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: &whitespace_excludes |
          (?x)^.*\.(md|rst|map|bin)$
      - id: end-of-file-fixer
        exclude: *whitespace_excludes
      - id: mixed-line-ending
        args: ['-f=lf']
      - id: double-quote-string-fixer
  - repo: https://github.com/espressif/astyle_py.git
    rev: v1.0.5
    hooks:
      - id: astyle_py
        args: ['--astyle-version=3.4.7', '--rules=astyle-rules.yml']
